// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/cards.proto

package cards

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                     // e.g., "ACTIVE", "INACTIVE", "FROZEN", "CLOSED"
	LastFour      string                 `protobuf:"bytes,4,opt,name=last_four,json=lastFour,proto3" json:"last_four,omitempty"` // pan_hash and cvv_hash are not included as per spec security notes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_proto_cards_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cards_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_proto_cards_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *Card) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Card) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Card) GetLastFour() string {
	if x != nil {
		return x.LastFour
	}
	return ""
}

type CreateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardType      string                 `protobuf:"bytes,2,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"` // e.g., "physical", "virtual"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardRequest) Reset() {
	*x = CreateCardRequest{}
	mi := &file_proto_cards_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardRequest) ProtoMessage() {}

func (x *CreateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cards_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardRequest.ProtoReflect.Descriptor instead.
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_cards_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCardRequest) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

type GetCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardRequest) Reset() {
	*x = GetCardRequest{}
	mi := &file_proto_cards_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardRequest) ProtoMessage() {}

func (x *GetCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cards_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardRequest.ProtoReflect.Descriptor instead.
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_cards_proto_rawDescGZIP(), []int{2}
}

func (x *GetCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type UpdateCardStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	NewStatus     string                 `protobuf:"bytes,2,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"` // e.g., "ACTIVE", "FROZEN"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardStatusRequest) Reset() {
	*x = UpdateCardStatusRequest{}
	mi := &file_proto_cards_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardStatusRequest) ProtoMessage() {}

func (x *UpdateCardStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cards_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_cards_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCardStatusRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *UpdateCardStatusRequest) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

var File_proto_cards_proto protoreflect.FileDescriptor

const file_proto_cards_proto_rawDesc = "" +
	"\n" +
	"\x11proto/cards.proto\"m\n" +
	"\x04Card\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\tlast_four\x18\x04 \x01(\tR\blastFour\"I\n" +
	"\x11CreateCardRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcard_type\x18\x02 \x01(\tR\bcardType\")\n" +
	"\x0eGetCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\"Q\n" +
	"\x17UpdateCardStatusRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x1d\n" +
	"\n" +
	"new_status\x18\x02 \x01(\tR\tnewStatus2\x88\x01\n" +
	"\x05Cards\x12'\n" +
	"\n" +
	"CreateCard\x12\x12.CreateCardRequest\x1a\x05.Card\x12!\n" +
	"\aGetCard\x12\x0f.GetCardRequest\x1a\x05.Card\x123\n" +
	"\x10UpdateCardStatus\x12\x18.UpdateCardStatusRequest\x1a\x05.CardB\tZ\a./cardsb\x06proto3"

var (
	file_proto_cards_proto_rawDescOnce sync.Once
	file_proto_cards_proto_rawDescData []byte
)

func file_proto_cards_proto_rawDescGZIP() []byte {
	file_proto_cards_proto_rawDescOnce.Do(func() {
		file_proto_cards_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cards_proto_rawDesc), len(file_proto_cards_proto_rawDesc)))
	})
	return file_proto_cards_proto_rawDescData
}

var file_proto_cards_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_cards_proto_goTypes = []any{
	(*Card)(nil),                    // 0: Card
	(*CreateCardRequest)(nil),       // 1: CreateCardRequest
	(*GetCardRequest)(nil),          // 2: GetCardRequest
	(*UpdateCardStatusRequest)(nil), // 3: UpdateCardStatusRequest
}
var file_proto_cards_proto_depIdxs = []int32{
	1, // 0: Cards.CreateCard:input_type -> CreateCardRequest
	2, // 1: Cards.GetCard:input_type -> GetCardRequest
	3, // 2: Cards.UpdateCardStatus:input_type -> UpdateCardStatusRequest
	0, // 3: Cards.CreateCard:output_type -> Card
	0, // 4: Cards.GetCard:output_type -> Card
	0, // 5: Cards.UpdateCardStatus:output_type -> Card
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cards_proto_init() }
func file_proto_cards_proto_init() {
	if File_proto_cards_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cards_proto_rawDesc), len(file_proto_cards_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cards_proto_goTypes,
		DependencyIndexes: file_proto_cards_proto_depIdxs,
		MessageInfos:      file_proto_cards_proto_msgTypes,
	}.Build()
	File_proto_cards_proto = out.File
	file_proto_cards_proto_goTypes = nil
	file_proto_cards_proto_depIdxs = nil
}
