// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/feed.proto

package feed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                // e.g., "TRANSACTION", "CARD_STATUS", "MESSAGE"
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`      // ISO 8601 string or similar
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`          // human-readable content or summary
	RefId         string                 `protobuf:"bytes,6,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"` // reference to another entity, e.g., transaction_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedItem) Reset() {
	*x = FeedItem{}
	mi := &file_proto_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedItem) ProtoMessage() {}

func (x *FeedItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedItem.ProtoReflect.Descriptor instead.
func (*FeedItem) Descriptor() ([]byte, []int) {
	return file_proto_feed_proto_rawDescGZIP(), []int{0}
}

func (x *FeedItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeedItem) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *FeedItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FeedItem) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *FeedItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FeedItem) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

type AddFeedItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	RefId         string                 `protobuf:"bytes,4,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // timestamp of the event
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFeedItemRequest) Reset() {
	*x = AddFeedItemRequest{}
	mi := &file_proto_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFeedItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFeedItemRequest) ProtoMessage() {}

func (x *AddFeedItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFeedItemRequest.ProtoReflect.Descriptor instead.
func (*AddFeedItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_feed_proto_rawDescGZIP(), []int{1}
}

func (x *AddFeedItemRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AddFeedItemRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddFeedItemRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddFeedItemRequest) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *AddFeedItemRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type FeedItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FeedItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedItems) Reset() {
	*x = FeedItems{}
	mi := &file_proto_feed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedItems) ProtoMessage() {}

func (x *FeedItems) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedItems.ProtoReflect.Descriptor instead.
func (*FeedItems) Descriptor() ([]byte, []int) {
	return file_proto_feed_proto_rawDescGZIP(), []int{2}
}

func (x *FeedItems) GetItems() []*FeedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListFeedItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	BeforeId      string                 `protobuf:"bytes,3,opt,name=before_id,json=beforeId,proto3" json:"before_id,omitempty"` // pagination cursor (feed item ID)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeedItemsRequest) Reset() {
	*x = ListFeedItemsRequest{}
	mi := &file_proto_feed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeedItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeedItemsRequest) ProtoMessage() {}

func (x *ListFeedItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeedItemsRequest.ProtoReflect.Descriptor instead.
func (*ListFeedItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_feed_proto_rawDescGZIP(), []int{3}
}

func (x *ListFeedItemsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListFeedItemsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFeedItemsRequest) GetBeforeId() string {
	if x != nil {
		return x.BeforeId
	}
	return ""
}

type FeedItemIDs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"` // list of feed item IDs to retrieve
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedItemIDs) Reset() {
	*x = FeedItemIDs{}
	mi := &file_proto_feed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedItemIDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedItemIDs) ProtoMessage() {}

func (x *FeedItemIDs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedItemIDs.ProtoReflect.Descriptor instead.
func (*FeedItemIDs) Descriptor() ([]byte, []int) {
	return file_proto_feed_proto_rawDescGZIP(), []int{4}
}

func (x *FeedItemIDs) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_proto_feed_proto protoreflect.FileDescriptor

const file_proto_feed_proto_rawDesc = "" +
	"\n" +
	"\x10proto/feed.proto\"\x9c\x01\n" +
	"\bFeedItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x15\n" +
	"\x06ref_id\x18\x06 \x01(\tR\x05refId\"\x96\x01\n" +
	"\x12AddFeedItemRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x15\n" +
	"\x06ref_id\x18\x04 \x01(\tR\x05refId\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\",\n" +
	"\tFeedItems\x12\x1f\n" +
	"\x05items\x18\x01 \x03(\v2\t.FeedItemR\x05items\"h\n" +
	"\x14ListFeedItemsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x1b\n" +
	"\tbefore_id\x18\x03 \x01(\tR\bbeforeId\"\x1f\n" +
	"\vFeedItemIDs\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids2\x97\x01\n" +
	"\x04Feed\x12-\n" +
	"\vAddFeedItem\x12\x13.AddFeedItemRequest\x1a\t.FeedItem\x122\n" +
	"\rListFeedItems\x12\x15.ListFeedItemsRequest\x1a\n" +
	".FeedItems\x12,\n" +
	"\x10GetFeedItemsByID\x12\f.FeedItemIDs\x1a\n" +
	".FeedItemsB\bZ\x06./feedb\x06proto3"

var (
	file_proto_feed_proto_rawDescOnce sync.Once
	file_proto_feed_proto_rawDescData []byte
)

func file_proto_feed_proto_rawDescGZIP() []byte {
	file_proto_feed_proto_rawDescOnce.Do(func() {
		file_proto_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_feed_proto_rawDesc), len(file_proto_feed_proto_rawDesc)))
	})
	return file_proto_feed_proto_rawDescData
}

var file_proto_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_feed_proto_goTypes = []any{
	(*FeedItem)(nil),             // 0: FeedItem
	(*AddFeedItemRequest)(nil),   // 1: AddFeedItemRequest
	(*FeedItems)(nil),            // 2: FeedItems
	(*ListFeedItemsRequest)(nil), // 3: ListFeedItemsRequest
	(*FeedItemIDs)(nil),          // 4: FeedItemIDs
}
var file_proto_feed_proto_depIdxs = []int32{
	0, // 0: FeedItems.items:type_name -> FeedItem
	1, // 1: Feed.AddFeedItem:input_type -> AddFeedItemRequest
	3, // 2: Feed.ListFeedItems:input_type -> ListFeedItemsRequest
	4, // 3: Feed.GetFeedItemsByID:input_type -> FeedItemIDs
	0, // 4: Feed.AddFeedItem:output_type -> FeedItem
	2, // 5: Feed.ListFeedItems:output_type -> FeedItems
	2, // 6: Feed.GetFeedItemsByID:output_type -> FeedItems
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_feed_proto_init() }
func file_proto_feed_proto_init() {
	if File_proto_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_feed_proto_rawDesc), len(file_proto_feed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_feed_proto_goTypes,
		DependencyIndexes: file_proto_feed_proto_depIdxs,
		MessageInfos:      file_proto_feed_proto_msgTypes,
	}.Build()
	File_proto_feed_proto = out.File
	file_proto_feed_proto_goTypes = nil
	file_proto_feed_proto_depIdxs = nil
}
