// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/merchant.proto

package merchant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MerchantID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantID) Reset() {
	*x = MerchantID{}
	mi := &file_proto_merchant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantID) ProtoMessage() {}

func (x *MerchantID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantID.ProtoReflect.Descriptor instead.
func (*MerchantID) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{0}
}

func (x *MerchantID) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type MerchantData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Mcc           int32                  `protobuf:"varint,5,opt,name=mcc,proto3" json:"mcc,omitempty"` // Merchant Category Code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantData) Reset() {
	*x = MerchantData{}
	mi := &file_proto_merchant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantData) ProtoMessage() {}

func (x *MerchantData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantData.ProtoReflect.Descriptor instead.
func (*MerchantData) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{1}
}

func (x *MerchantData) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *MerchantData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MerchantData) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MerchantData) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *MerchantData) GetMcc() int32 {
	if x != nil {
		return x.Mcc
	}
	return 0
}

type MerchantQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawName       string                 `protobuf:"bytes,1,opt,name=raw_name,json=rawName,proto3" json:"raw_name,omitempty"`
	Mcc           int32                  `protobuf:"varint,2,opt,name=mcc,proto3" json:"mcc,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"` // optional city for lookup
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantQuery) Reset() {
	*x = MerchantQuery{}
	mi := &file_proto_merchant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantQuery) ProtoMessage() {}

func (x *MerchantQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantQuery.ProtoReflect.Descriptor instead.
func (*MerchantQuery) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{2}
}

func (x *MerchantQuery) GetRawName() string {
	if x != nil {
		return x.RawName
	}
	return ""
}

func (x *MerchantQuery) GetMcc() int32 {
	if x != nil {
		return x.Mcc
	}
	return 0
}

func (x *MerchantQuery) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type UpdateMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                      // optional new name
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`              // optional new category
	LogoUrl       string                 `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"` // optional new logo URL
	Mcc           int32                  `protobuf:"varint,5,opt,name=mcc,proto3" json:"mcc,omitempty"`                       // optional new MCC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMerchantRequest) Reset() {
	*x = UpdateMerchantRequest{}
	mi := &file_proto_merchant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantRequest) ProtoMessage() {}

func (x *UpdateMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merchant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantRequest.ProtoReflect.Descriptor instead.
func (*UpdateMerchantRequest) Descriptor() ([]byte, []int) {
	return file_proto_merchant_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMerchantRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *UpdateMerchantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMerchantRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateMerchantRequest) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *UpdateMerchantRequest) GetMcc() int32 {
	if x != nil {
		return x.Mcc
	}
	return 0
}

var File_proto_merchant_proto protoreflect.FileDescriptor

const file_proto_merchant_proto_rawDesc = "" +
	"\n" +
	"\x14proto/merchant.proto\"-\n" +
	"\n" +
	"MerchantID\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\"\x8c\x01\n" +
	"\fMerchantData\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x19\n" +
	"\blogo_url\x18\x04 \x01(\tR\alogoUrl\x12\x10\n" +
	"\x03mcc\x18\x05 \x01(\x05R\x03mcc\"P\n" +
	"\rMerchantQuery\x12\x19\n" +
	"\braw_name\x18\x01 \x01(\tR\arawName\x12\x10\n" +
	"\x03mcc\x18\x02 \x01(\x05R\x03mcc\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\"\x95\x01\n" +
	"\x15UpdateMerchantRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x19\n" +
	"\blogo_url\x18\x04 \x01(\tR\alogoUrl\x12\x10\n" +
	"\x03mcc\x18\x05 \x01(\x05R\x03mcc2\xa5\x01\n" +
	"\bMerchant\x12)\n" +
	"\vGetMerchant\x12\v.MerchantID\x1a\r.MerchantData\x125\n" +
	"\x14FindOrCreateMerchant\x12\x0e.MerchantQuery\x1a\r.MerchantData\x127\n" +
	"\x0eUpdateMerchant\x12\x16.UpdateMerchantRequest\x1a\r.MerchantDataB\fZ\n" +
	"./merchantb\x06proto3"

var (
	file_proto_merchant_proto_rawDescOnce sync.Once
	file_proto_merchant_proto_rawDescData []byte
)

func file_proto_merchant_proto_rawDescGZIP() []byte {
	file_proto_merchant_proto_rawDescOnce.Do(func() {
		file_proto_merchant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_merchant_proto_rawDesc), len(file_proto_merchant_proto_rawDesc)))
	})
	return file_proto_merchant_proto_rawDescData
}

var file_proto_merchant_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_merchant_proto_goTypes = []any{
	(*MerchantID)(nil),            // 0: MerchantID
	(*MerchantData)(nil),          // 1: MerchantData
	(*MerchantQuery)(nil),         // 2: MerchantQuery
	(*UpdateMerchantRequest)(nil), // 3: UpdateMerchantRequest
}
var file_proto_merchant_proto_depIdxs = []int32{
	0, // 0: Merchant.GetMerchant:input_type -> MerchantID
	2, // 1: Merchant.FindOrCreateMerchant:input_type -> MerchantQuery
	3, // 2: Merchant.UpdateMerchant:input_type -> UpdateMerchantRequest
	1, // 3: Merchant.GetMerchant:output_type -> MerchantData
	1, // 4: Merchant.FindOrCreateMerchant:output_type -> MerchantData
	1, // 5: Merchant.UpdateMerchant:output_type -> MerchantData
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_merchant_proto_init() }
func file_proto_merchant_proto_init() {
	if File_proto_merchant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_merchant_proto_rawDesc), len(file_proto_merchant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_merchant_proto_goTypes,
		DependencyIndexes: file_proto_merchant_proto_depIdxs,
		MessageInfos:      file_proto_merchant_proto_msgTypes,
	}.Build()
	File_proto_merchant_proto = out.File
	file_proto_merchant_proto_goTypes = nil
	file_proto_merchant_proto_depIdxs = nil
}
