// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/disco_payment_gateway.proto

package disco_payment_gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Based on GLIDE.md, request body contains payment parameters and blockchain data
	// Define fields based on typical payment session creation needs
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // Assuming a link to our internal user
	Currency      string `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`                          // Target currency for payment
	Amount        int64  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                             // Target amount in minor units
	RedirectUrl   string `protobuf:"bytes,4,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"` // URL to redirect after payment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_disco_payment_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSessionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateSessionRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateSessionRequest) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                           // e.g., "pending", "ready"
	PaymentUrl    string                 `protobuf:"bytes,3,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"` // URL for the user to complete payment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_disco_payment_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateSessionResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

type GetSessionByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionByIdRequest) Reset() {
	*x = GetSessionByIdRequest{}
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionByIdRequest) ProtoMessage() {}

func (x *GetSessionByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionByIdRequest.ProtoReflect.Descriptor instead.
func (*GetSessionByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_disco_payment_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *GetSessionByIdRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionByPaymentTransactionRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	PaymentTransactionHash string                 `protobuf:"bytes,1,opt,name=payment_transaction_hash,json=paymentTransactionHash,proto3" json:"payment_transaction_hash,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetSessionByPaymentTransactionRequest) Reset() {
	*x = GetSessionByPaymentTransactionRequest{}
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionByPaymentTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionByPaymentTransactionRequest) ProtoMessage() {}

func (x *GetSessionByPaymentTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionByPaymentTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionByPaymentTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_disco_payment_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *GetSessionByPaymentTransactionRequest) GetPaymentTransactionHash() string {
	if x != nil {
		return x.PaymentTransactionHash
	}
	return ""
}

type GetSessionResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SessionId              string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status                 string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	UserId                 string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency               string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount                 int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentTransactionHash string                 `protobuf:"bytes,6,opt,name=payment_transaction_hash,json=paymentTransactionHash,proto3" json:"payment_transaction_hash,omitempty"` // Optional, if linked
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_disco_payment_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *GetSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetSessionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSessionResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetSessionResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetSessionResponse) GetPaymentTransactionHash() string {
	if x != nil {
		return x.PaymentTransactionHash
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Filter by user
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`               // Filter by status (optional)
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                // Pagination limit (optional)
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`               // Pagination cursor (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_disco_payment_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *ListSessionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListSessionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSessionsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*GetSessionResponse  `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`                       // Reuse GetSessionResponse for items
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // For pagination (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_disco_payment_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *ListSessionsResponse) GetSessions() []*GetSessionResponse {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type CreateWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Link to our internal user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_proto_disco_payment_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *CreateWalletRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletAddress string                 `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"` // Add more fields as needed (e.g., chain)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletResponse) Reset() {
	*x = CreateWalletResponse{}
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletResponse) ProtoMessage() {}

func (x *CreateWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletResponse.ProtoReflect.Descriptor instead.
func (*CreateWalletResponse) Descriptor() ([]byte, []int) {
	return file_proto_disco_payment_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *CreateWalletResponse) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

type EstimatePaymentAmountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetCurrency string                 `protobuf:"bytes,1,opt,name=target_currency,json=targetCurrency,proto3" json:"target_currency,omitempty"`
	TargetAmount   int64                  `protobuf:"varint,2,opt,name=target_amount,json=targetAmount,proto3" json:"target_amount,omitempty"`      // Amount in target currency minor units
	SourceCurrency string                 `protobuf:"bytes,3,opt,name=source_currency,json=sourceCurrency,proto3" json:"source_currency,omitempty"` // Currency user will pay with (optional)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EstimatePaymentAmountRequest) Reset() {
	*x = EstimatePaymentAmountRequest{}
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimatePaymentAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimatePaymentAmountRequest) ProtoMessage() {}

func (x *EstimatePaymentAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimatePaymentAmountRequest.ProtoReflect.Descriptor instead.
func (*EstimatePaymentAmountRequest) Descriptor() ([]byte, []int) {
	return file_proto_disco_payment_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *EstimatePaymentAmountRequest) GetTargetCurrency() string {
	if x != nil {
		return x.TargetCurrency
	}
	return ""
}

func (x *EstimatePaymentAmountRequest) GetTargetAmount() int64 {
	if x != nil {
		return x.TargetAmount
	}
	return 0
}

func (x *EstimatePaymentAmountRequest) GetSourceCurrency() string {
	if x != nil {
		return x.SourceCurrency
	}
	return ""
}

type EstimatePaymentAmountResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EstimatedAmount int64                  `protobuf:"varint,1,opt,name=estimated_amount,json=estimatedAmount,proto3" json:"estimated_amount,omitempty"` // Amount in source currency minor units
	SourceCurrency  string                 `protobuf:"bytes,2,opt,name=source_currency,json=sourceCurrency,proto3" json:"source_currency,omitempty"`     // Add more fields as needed (e.g., fees, expiry)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EstimatePaymentAmountResponse) Reset() {
	*x = EstimatePaymentAmountResponse{}
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimatePaymentAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimatePaymentAmountResponse) ProtoMessage() {}

func (x *EstimatePaymentAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_disco_payment_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimatePaymentAmountResponse.ProtoReflect.Descriptor instead.
func (*EstimatePaymentAmountResponse) Descriptor() ([]byte, []int) {
	return file_proto_disco_payment_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *EstimatePaymentAmountResponse) GetEstimatedAmount() int64 {
	if x != nil {
		return x.EstimatedAmount
	}
	return 0
}

func (x *EstimatePaymentAmountResponse) GetSourceCurrency() string {
	if x != nil {
		return x.SourceCurrency
	}
	return ""
}

var File_proto_disco_payment_gateway_proto protoreflect.FileDescriptor

const file_proto_disco_payment_gateway_proto_rawDesc = "" +
	"\n" +
	"!proto/disco_payment_gateway.proto\"\x86\x01\n" +
	"\x14CreateSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12!\n" +
	"\fredirect_url\x18\x04 \x01(\tR\vredirectUrl\"o\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vpayment_url\x18\x03 \x01(\tR\n" +
	"paymentUrl\"6\n" +
	"\x15GetSessionByIdRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"a\n" +
	"%GetSessionByPaymentTransactionRequest\x128\n" +
	"\x18payment_transaction_hash\x18\x01 \x01(\tR\x16paymentTransactionHash\"\xd2\x01\n" +
	"\x12GetSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x128\n" +
	"\x18payment_transaction_hash\x18\x06 \x01(\tR\x16paymentTransactionHash\"t\n" +
	"\x13ListSessionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\"h\n" +
	"\x14ListSessionsResponse\x12/\n" +
	"\bsessions\x18\x01 \x03(\v2\x13.GetSessionResponseR\bsessions\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\".\n" +
	"\x13CreateWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"=\n" +
	"\x14CreateWalletResponse\x12%\n" +
	"\x0ewallet_address\x18\x01 \x01(\tR\rwalletAddress\"\x95\x01\n" +
	"\x1cEstimatePaymentAmountRequest\x12'\n" +
	"\x0ftarget_currency\x18\x01 \x01(\tR\x0etargetCurrency\x12#\n" +
	"\rtarget_amount\x18\x02 \x01(\x03R\ftargetAmount\x12'\n" +
	"\x0fsource_currency\x18\x03 \x01(\tR\x0esourceCurrency\"s\n" +
	"\x1dEstimatePaymentAmountResponse\x12)\n" +
	"\x10estimated_amount\x18\x01 \x01(\x03R\x0festimatedAmount\x12'\n" +
	"\x0fsource_currency\x18\x02 \x01(\tR\x0esourceCurrency2\xc5\x03\n" +
	"\x13DiscoPaymentGateway\x12>\n" +
	"\rCreateSession\x12\x15.CreateSessionRequest\x1a\x16.CreateSessionResponse\x12=\n" +
	"\x0eGetSessionById\x12\x16.GetSessionByIdRequest\x1a\x13.GetSessionResponse\x12;\n" +
	"\fListSessions\x12\x14.ListSessionsRequest\x1a\x15.ListSessionsResponse\x12]\n" +
	"\x1eGetSessionByPaymentTransaction\x12&.GetSessionByPaymentTransactionRequest\x1a\x13.GetSessionResponse\x12;\n" +
	"\fCreateWallet\x12\x14.CreateWalletRequest\x1a\x15.CreateWalletResponse\x12V\n" +
	"\x15EstimatePaymentAmount\x12\x1d.EstimatePaymentAmountRequest\x1a\x1e.EstimatePaymentAmountResponseB\x19Z\x17./disco_payment_gatewayb\x06proto3"

var (
	file_proto_disco_payment_gateway_proto_rawDescOnce sync.Once
	file_proto_disco_payment_gateway_proto_rawDescData []byte
)

func file_proto_disco_payment_gateway_proto_rawDescGZIP() []byte {
	file_proto_disco_payment_gateway_proto_rawDescOnce.Do(func() {
		file_proto_disco_payment_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_disco_payment_gateway_proto_rawDesc), len(file_proto_disco_payment_gateway_proto_rawDesc)))
	})
	return file_proto_disco_payment_gateway_proto_rawDescData
}

var file_proto_disco_payment_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_disco_payment_gateway_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),                  // 0: CreateSessionRequest
	(*CreateSessionResponse)(nil),                 // 1: CreateSessionResponse
	(*GetSessionByIdRequest)(nil),                 // 2: GetSessionByIdRequest
	(*GetSessionByPaymentTransactionRequest)(nil), // 3: GetSessionByPaymentTransactionRequest
	(*GetSessionResponse)(nil),                    // 4: GetSessionResponse
	(*ListSessionsRequest)(nil),                   // 5: ListSessionsRequest
	(*ListSessionsResponse)(nil),                  // 6: ListSessionsResponse
	(*CreateWalletRequest)(nil),                   // 7: CreateWalletRequest
	(*CreateWalletResponse)(nil),                  // 8: CreateWalletResponse
	(*EstimatePaymentAmountRequest)(nil),          // 9: EstimatePaymentAmountRequest
	(*EstimatePaymentAmountResponse)(nil),         // 10: EstimatePaymentAmountResponse
}
var file_proto_disco_payment_gateway_proto_depIdxs = []int32{
	4,  // 0: ListSessionsResponse.sessions:type_name -> GetSessionResponse
	0,  // 1: DiscoPaymentGateway.CreateSession:input_type -> CreateSessionRequest
	2,  // 2: DiscoPaymentGateway.GetSessionById:input_type -> GetSessionByIdRequest
	5,  // 3: DiscoPaymentGateway.ListSessions:input_type -> ListSessionsRequest
	3,  // 4: DiscoPaymentGateway.GetSessionByPaymentTransaction:input_type -> GetSessionByPaymentTransactionRequest
	7,  // 5: DiscoPaymentGateway.CreateWallet:input_type -> CreateWalletRequest
	9,  // 6: DiscoPaymentGateway.EstimatePaymentAmount:input_type -> EstimatePaymentAmountRequest
	1,  // 7: DiscoPaymentGateway.CreateSession:output_type -> CreateSessionResponse
	4,  // 8: DiscoPaymentGateway.GetSessionById:output_type -> GetSessionResponse
	6,  // 9: DiscoPaymentGateway.ListSessions:output_type -> ListSessionsResponse
	4,  // 10: DiscoPaymentGateway.GetSessionByPaymentTransaction:output_type -> GetSessionResponse
	8,  // 11: DiscoPaymentGateway.CreateWallet:output_type -> CreateWalletResponse
	10, // 12: DiscoPaymentGateway.EstimatePaymentAmount:output_type -> EstimatePaymentAmountResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_disco_payment_gateway_proto_init() }
func file_proto_disco_payment_gateway_proto_init() {
	if File_proto_disco_payment_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_disco_payment_gateway_proto_rawDesc), len(file_proto_disco_payment_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_disco_payment_gateway_proto_goTypes,
		DependencyIndexes: file_proto_disco_payment_gateway_proto_depIdxs,
		MessageInfos:      file_proto_disco_payment_gateway_proto_msgTypes,
	}.Build()
	File_proto_disco_payment_gateway_proto = out.File
	file_proto_disco_payment_gateway_proto_goTypes = nil
	file_proto_disco_payment_gateway_proto_depIdxs = nil
}
