// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/card_processing.proto

package card_processing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CardProcessing_AuthorizeCardTransaction_FullMethodName = "/CardProcessing/AuthorizeCardTransaction"
)

// CardProcessingClient is the client API for CardProcessing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CardProcessingClient interface {
	AuthorizeCardTransaction(ctx context.Context, in *CardAuthRequest, opts ...grpc.CallOption) (*CardAuthReply, error)
}

type cardProcessingClient struct {
	cc grpc.ClientConnInterface
}

func NewCardProcessingClient(cc grpc.ClientConnInterface) CardProcessingClient {
	return &cardProcessingClient{cc}
}

func (c *cardProcessingClient) AuthorizeCardTransaction(ctx context.Context, in *CardAuthRequest, opts ...grpc.CallOption) (*CardAuthReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardAuthReply)
	err := c.cc.Invoke(ctx, CardProcessing_AuthorizeCardTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardProcessingServer is the server API for CardProcessing service.
// All implementations must embed UnimplementedCardProcessingServer
// for forward compatibility.
type CardProcessingServer interface {
	AuthorizeCardTransaction(context.Context, *CardAuthRequest) (*CardAuthReply, error)
	mustEmbedUnimplementedCardProcessingServer()
}

// UnimplementedCardProcessingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCardProcessingServer struct{}

func (UnimplementedCardProcessingServer) AuthorizeCardTransaction(context.Context, *CardAuthRequest) (*CardAuthReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizeCardTransaction not implemented")
}
func (UnimplementedCardProcessingServer) mustEmbedUnimplementedCardProcessingServer() {}
func (UnimplementedCardProcessingServer) testEmbeddedByValue()                        {}

// UnsafeCardProcessingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CardProcessingServer will
// result in compilation errors.
type UnsafeCardProcessingServer interface {
	mustEmbedUnimplementedCardProcessingServer()
}

func RegisterCardProcessingServer(s grpc.ServiceRegistrar, srv CardProcessingServer) {
	// If the following call pancis, it indicates UnimplementedCardProcessingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CardProcessing_ServiceDesc, srv)
}

func _CardProcessing_AuthorizeCardTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardProcessingServer).AuthorizeCardTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardProcessing_AuthorizeCardTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardProcessingServer).AuthorizeCardTransaction(ctx, req.(*CardAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CardProcessing_ServiceDesc is the grpc.ServiceDesc for CardProcessing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CardProcessing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CardProcessing",
	HandlerType: (*CardProcessingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthorizeCardTransaction",
			Handler:    _CardProcessing_AuthorizeCardTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/card_processing.proto",
}
