// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/card_processing.proto

package card_processing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // amount in cents
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	MerchantId    string                 `protobuf:"bytes,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`       // optional merchant ID
	MerchantName  string                 `protobuf:"bytes,5,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"` // raw merchant name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardAuthRequest) Reset() {
	*x = CardAuthRequest{}
	mi := &file_proto_card_processing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardAuthRequest) ProtoMessage() {}

func (x *CardAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_processing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardAuthRequest.ProtoReflect.Descriptor instead.
func (*CardAuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_card_processing_proto_rawDescGZIP(), []int{0}
}

func (x *CardAuthRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CardAuthRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CardAuthRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CardAuthRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *CardAuthRequest) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

type CardAuthReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	DeclineReason string                 `protobuf:"bytes,2,opt,name=decline_reason,json=declineReason,proto3" json:"decline_reason,omitempty"` // reason if not approved
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardAuthReply) Reset() {
	*x = CardAuthReply{}
	mi := &file_proto_card_processing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardAuthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardAuthReply) ProtoMessage() {}

func (x *CardAuthReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_card_processing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardAuthReply.ProtoReflect.Descriptor instead.
func (*CardAuthReply) Descriptor() ([]byte, []int) {
	return file_proto_card_processing_proto_rawDescGZIP(), []int{1}
}

func (x *CardAuthReply) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *CardAuthReply) GetDeclineReason() string {
	if x != nil {
		return x.DeclineReason
	}
	return ""
}

var File_proto_card_processing_proto protoreflect.FileDescriptor

const file_proto_card_processing_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/card_processing.proto\"\xa4\x01\n" +
	"\x0fCardAuthRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x1f\n" +
	"\vmerchant_id\x18\x04 \x01(\tR\n" +
	"merchantId\x12#\n" +
	"\rmerchant_name\x18\x05 \x01(\tR\fmerchantName\"R\n" +
	"\rCardAuthReply\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12%\n" +
	"\x0edecline_reason\x18\x02 \x01(\tR\rdeclineReason2N\n" +
	"\x0eCardProcessing\x12<\n" +
	"\x18AuthorizeCardTransaction\x12\x10.CardAuthRequest\x1a\x0e.CardAuthReplyB\x13Z\x11./card_processingb\x06proto3"

var (
	file_proto_card_processing_proto_rawDescOnce sync.Once
	file_proto_card_processing_proto_rawDescData []byte
)

func file_proto_card_processing_proto_rawDescGZIP() []byte {
	file_proto_card_processing_proto_rawDescOnce.Do(func() {
		file_proto_card_processing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_card_processing_proto_rawDesc), len(file_proto_card_processing_proto_rawDesc)))
	})
	return file_proto_card_processing_proto_rawDescData
}

var file_proto_card_processing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_card_processing_proto_goTypes = []any{
	(*CardAuthRequest)(nil), // 0: CardAuthRequest
	(*CardAuthReply)(nil),   // 1: CardAuthReply
}
var file_proto_card_processing_proto_depIdxs = []int32{
	0, // 0: CardProcessing.AuthorizeCardTransaction:input_type -> CardAuthRequest
	1, // 1: CardProcessing.AuthorizeCardTransaction:output_type -> CardAuthReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_card_processing_proto_init() }
func file_proto_card_processing_proto_init() {
	if File_proto_card_processing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_card_processing_proto_rawDesc), len(file_proto_card_processing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_card_processing_proto_goTypes,
		DependencyIndexes: file_proto_card_processing_proto_depIdxs,
		MessageInfos:      file_proto_card_processing_proto_msgTypes,
	}.Build()
	File_proto_card_processing_proto = out.File
	file_proto_card_processing_proto_goTypes = nil
	file_proto_card_processing_proto_depIdxs = nil
}
